# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2498980b4aba90cb55b0e2268508c02aca470016214a7b91b6bf06e9d864ee6afe41aadfcc92996ea80755e54d84bd54d533135b75afaa14daa71589d16c94c

test:
  secret_key_base: 784df771c1ac6c9f7aea00f79c9c520dfc326af577c0a955300ccb6619aa6a32c74e1f5d5ae616d24f695d3fa1f76461d8a6b826d440f5ae4180901089bfd9ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
